export const SET_REQUEST_IN_PROCESS = "SET_REQUEST_IN_PROCESS";
export const REQUEST_REQUESTED = "REQUEST_REQUESTED";
export const REQUEST_RECEIVED = "REQUEST_RECEIVED";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const SORT_DATA = "SORT_DATA";
export const FILTER_DATA = "FILTER_DATA";
